"use client";

import { useEffect, useState } from "react";
import dynamic from "next/dynamic";

const MonacoEditor = dynamic(() => import("@monaco-editor/react"), {
  ssr: false,
  });

  export default function FileEditor() {
    const [tree, setTree] = useState<any[]>([]);
      const [file, setFile] = useState<string | null>(null);
        const [code, setCode] = useState("");
          const [search, setSearch] = useState("");
            const [results, setResults] = useState<any[]>([]);

              async function api(body: any) {
                  return fetch("/api/file-manager", {
                        method: "POST",
                              body: JSON.stringify(body),
                                  }).then((r) => r.json());
                                    }

                                      async function loadTree() {
                                          setTree(await api({ action: "tree" }));
                                            }

                                              async function openFile(p: string) {
                                                  const r = await api({ action: "read", filePath: p });
                                                      setFile(p);
                                                          setCode(r.content);
                                                            }

                                                              async function save() {
                                                                  await api({ action: "save", filePath: file, content: code });
                                                                    }

                                                                      async function empty() {
                                                                          await api({ action: "empty", filePath: file });
                                                                              setCode("");
                                                                                }

                                                                                  async function del() {
                                                                                      await api({ action: "delete", filePath: file });
                                                                                          setFile(null);
                                                                                              setCode("");
                                                                                                  loadTree();
                                                                                                    }

                                                                                                      async function runSearch() {
                                                                                                          setResults(await api({ action: "search", content: search }));
                                                                                                            }

                                                                                                              useEffect(() => {
                                                                                                                  loadTree();
                                                                                                                    }, []);

                                                                                                                      const renderTree = (nodes: any[]) =>
                                                                                                                          nodes.map((n) => (
                                                                                                                                <div key={n.path} className="ml-3">
                                                                                                                                        {n.type === "file" ? (
                                                                                                                                                  <div
                                                                                                                                                              className="cursor-pointer hover:text-blue-600"
                                                                                                                                                                          onClick={() => openFile(n.path)}
                                                                                                                                                                                    >
                                                                                                                                                                                                📄 {n.name}
                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                  ) : (
                                                                                                                                                                                                                            <>
                                                                                                                                                                                                                                        📁 {n.name}
                                                                                                                                                                                                                                                    {renderTree(n.children)}
                                                                                                                                                                                                                                                              </>
                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                ));

                                                                                                                                                                                                                                                                                  return (
                                                                                                                                                                                                                                                                                      <div className="flex h-screen">
                                                                                                                                                                                                                                                                                            {/* LEFT PANEL */}
                                                                                                                                                                                                                                                                                                  <div className="w-72 border-r p-2 overflow-auto">
                                                                                                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                                                                                                    className="mb-2 bg-green-600 text-white px-2 py-1"
                                                                                                                                                                                                                                                                                                                              onClick={loadTree}
                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                Refresh
                                                                                                                                                                                                                                                                                                                                                        </button>

                                                                                                                                                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                                                                                                                                                          className="border w-full mb-2 px-2"
                                                                                                                                                                                                                                                                                                                                                                                    placeholder="Search..."
                                                                                                                                                                                                                                                                                                                                                                                              value={search}
                                                                                                                                                                                                                                                                                                                                                                                                        onChange={(e) => setSearch(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                                                                                                                                                                  className="bg-blue-600 text-white w-full mb-2"
                                                                                                                                                                                                                                                                                                                                                                                                                                            onClick={runSearch}
                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                              Search
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {results.map((r, i) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    key={i}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="text-xs cursor-pointer hover:text-blue-600"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onClick={() => openFile(r.file)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {r.file}:{r.line}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {renderTree(tree)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* EDITOR */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="flex-1 flex flex-col">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="p-2 border-b flex gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button onClick={save} className="bg-blue-600 text-white px-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Save
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button onClick={empty} className="bg-yellow-600 text-white px-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Empty
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button onClick={del} className="bg-red-600 text-white px-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Delete
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="flex-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <MonacoEditor
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            language={file?.endsWith(".tsx") ? "typescript" : "javascript"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        theme="vs-dark"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    value={code}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onChange={(v) => setCode(v || "")}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onMount={(editor, monaco) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          monaco.languages.typescript.typescriptDefaults.setDiagnosticsOptions(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            noSemanticValidation: false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              noSyntaxValidation: false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          monaco.languages.typescript.typescriptDefaults.setCompilerOptions({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          target:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            monaco.languages.typescript.ScriptTarget.ESNext,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            jsx: monaco.languages.typescript.JsxEmit.React,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            module:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              monaco.languages.typescript.ModuleKind.ESNext,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              moduleResolution:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                monaco.languages.typescript.ModuleResolutionKind.NodeJs,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                strict: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                esModuleInterop: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      options={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    minimap: { enabled: false },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  automaticLayout: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fontSize: 14,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }