import { NextResponse } from "next/server";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import fs from "fs";
import path from "path";
import Database from "better-sqlite3";

const toArabicDigits = (v: string | number) =>
  String(v).replace(/\d/g, d => "٠١٢٣٤٥٦٧٨٩"[Number(d)]);

  const getDbPath = () => path.join(process.cwd(), "src", "data", "educators.db");

  function applyTextStyle(doc: jsPDF, styleObj: any) {
    const fontName = "Amiri";
      let style = "normal";
        if (styleObj.bold && styleObj.italic) style = "bolditalic";
          else if (styleObj.bold) style = "bold";
            else if (styleObj.italic) style = "italic";
              doc.setFont(fontName, style);
                doc.setFontSize(styleObj.fontSize || 10);
                  doc.setTextColor(styleObj.textColor || "#000000");
                  }

                  function drawInfoBox(doc: jsPDF, label: string, value: string, xRight: number, y: number, style: any) {
                    const padding = 2;
                      const labelW = (style.labelWidth || 25);
                        const valueW = style.width || 60;
                          const h = style.height || 8;
                            if (style.labelBgColor) {
                                doc.setFillColor(style.labelBgColor);
                                    doc.rect(xRight - labelW, y, labelW, h, "F");
                                      }
                                        if (style.valueBgColor) {
                                            doc.setFillColor(style.valueBgColor);
                                                doc.rect(xRight - labelW - valueW - 2, y, valueW, h, "F");
                                                  }
                                                    doc.setLineWidth(0.3);
                                                      doc.setDrawColor(0);
                                                        applyTextStyle(doc, style);
                                                          doc.rect(xRight - labelW, y, labelW, h);
                                                            doc.text(label, xRight - padding, y + 5, { align: "right" });
                                                              doc.rect(xRight - labelW - valueW - 2, y, valueW, h);
                                                                const lines = doc.splitTextToSize(value || "", valueW - 2);
                                                                  doc.text(lines, xRight - labelW - 4, y + 5, { align: "right" });
                                                                  }

                                                                  function drawPageFrame(doc: jsPDF, settings: any, project: any, hall: any, pageNumber: number) {
                                                                    const pageW = doc.internal.pageSize.getWidth();
                                                                      const pageH = doc.internal.pageSize.getHeight();
                                                                        doc.setLineWidth(1.5);
                                                                          doc.setDrawColor(settings.borderColor || "#000000");
                                                                            doc.rect(5, 5, pageW - 10, pageH - 10);
                                                                              const tts = settings.titleStyle;
                                                                                doc.setFillColor(tts.bgColor);
                                                                                  doc.rect(45, 10, pageW - 90, tts.height || 7, "F");
                                                                                    applyTextStyle(doc, tts);
                                                                                      doc.text(settings.title, pageW / 2, 10 + (tts.height || 7) / 2 + 1, { align: "center", baseline: "middle" });
                                                                                        // Logo
                                                                                          const lX = 15; const lY = 8;
                                                                                            doc.setFillColor(40, 60, 80);
                                                                                              doc.rect(lX, lY, 6, 15, "F");
                                                                                                doc.setTextColor(255); doc.setFontSize(10); doc.setFont("helvetica", "bold");
                                                                                                  doc.text("S", lX + 3, lY + 4, { align: "center", baseline: "middle" });
                                                                                                    doc.text("F", lX + 3, lY + 8, { align: "center", baseline: "middle" });
                                                                                                      doc.text("D", lX + 3, lY + 12, { align: "center", baseline: "middle" });
                                                                                                        doc.setFont("Amiri", "normal"); doc.setTextColor(40, 60, 80); doc.setFontSize(11);
                                                                                                          doc.text("الصندوق", lX + 8, lY + 4);
                                                                                                            doc.text("الاجتماعي", lX + 8, lY + 9);
                                                                                                              doc.text("للتنمية", lX + 8, lY + 14);
                                                                                                                doc.setFontSize(6); doc.text("Social Fund for Development", lX, lY + 18);
                                                                                                                  const ibs = settings.infoBoxStyle;
                                                                                                                    drawInfoBox(doc, "رقم المشروع", toArabicDigits(project.projectId), pageW - 10, 26, ibs);
                                                                                                                      drawInfoBox(doc, "اسم المشروع", project.projectName, pageW - 10, 36, ibs);
                                                                                                                        drawInfoBox(doc, "رقم القاعة", toArabicDigits(hall.hallNo), 90, 26, ibs);
                                                                                                                          drawInfoBox(doc, "اسم القاعة", hall.hallName, 90, 36, ibs);
                                                                                                                            const fts = settings.footerStyle;
                                                                                                                              const fY = pageH - 25;
                                                                                                                                applyTextStyle(doc, fts);
                                                                                                                                  doc.text("الاسم:", pageW - 15, fY, { align: "right" });
                                                                                                                                    doc.line(pageW - 50, fY + 1, pageW - 100, fY + 1);
                                                                                                                                      doc.text("الصفة:", pageW - 15, fY + 8, { align: "right" });
                                                                                                                                        doc.line(pageW - 50, fY + 9, pageW - 100, fY + 9);
                                                                                                                                          doc.rect(55, fY - 5, 40, 20);
                                                                                                                                            doc.text("توقيع اللجنة", 75, fY + 5, { align: "center" });
                                                                                                                                              doc.rect(10, fY - 5, 40, 20);
                                                                                                                                                doc.text("ختم المديرية", 30, fY + 5, { align: "center" });
                                                                                                                                                  doc.text(`صفحة ${toArabicDigits(pageNumber)}`, pageW / 2, pageH - 10, { align: "center" });
                                                                                                                                                  }

                                                                                                                                                  export async function POST(req: Request) {
                                                                                                                                                    try {
                                                                                                                                                        const { projectId, settings } = await req.json();
                                                                                                                                                            const db = new Database(getDbPath());
                                                                                                                                                                const project = db.prepare("SELECT * FROM projects WHERE projectId = ?").get(projectId) as any;
                                                                                                                                                                    const rows = db.prepare("SELECT * FROM educators WHERE project_id = ? AND interview_hall_no IS NOT NULL ORDER BY interview_hall_no, total_score DESC").all(projectId);
                                                                                                                                                                        db.close();
                                                                                                                                                                            const doc = new jsPDF({ orientation: settings.pageOrientation, unit: "mm", format: settings.pageSize });
                                                                                                                                                                                // Load Fonts
                                                                                                                                                                                    ["Regular", "Bold", "Italic", "BoldItalic"].forEach(s => {
                                                                                                                                                                                          const p = path.join(process.cwd(), `public/fonts/Amiri-${s}.ttf`);
                                                                                                                                                                                                if (fs.existsSync(p)) doc.addFileToVFS(`Amiri-${s}.ttf`, b64);
                                                                                                                                                                                                      doc.addFont(`Amiri-${s}.ttf`, "Amiri", s.toLowerCase() === "regular" ? "normal" : s.toLowerCase());
                                                                                                                                                                                                          });
                                                                                                                                                                                                              doc.setFont("Amiri", "normal");
                                                                                                                                                                                                                  const grouped = rows.reduce((acc: any, r: any) => {
                                                                                                                                                                                                                        acc[r.interview_hall_no] ??= { hallNo: r.interview_hall_no, hallName: r.interview_hall_name, rows: [] };
                                                                                                                                                                                                                              acc[r.interview_hall_no].rows.push(r);
                                                                                                                                                                                                                                    return acc;
                                                                                                                                                                                                                                        }, {});
                                                                                                                                                                                                                                            let isFirst = true;
                                                                                                                                                                                                                                                for (const key in grouped) {
                                                                                                                                                                                                                                                      if (!isFirst) doc.addPage();
                                                                                                                                                                                                                                                            isFirst = false;
                                                                                                                                                                                                                                                                  const hall = grouped[key];
                                                                                                                                                                                                                                                                        const cols = [...settings.tableColumns].reverse();
                                                                                                                                                                                                                                                                              const columnStyles: any = {};
                                                                                                                                                                                                                                                                                    cols.forEach((c, idx) => {
                                                                                                                                                                                                                                                                                            columnStyles[idx] = {
                                                                                                                                                                                                                                                                                                      cellWidth: c.width,
                                                                                                                                                                                                                                                                                                                fillColor: c.cellBgColor,
                                                                                                                                                                                                                                                                                                                          textColor: c.cellTextColor,
                                                                                                                                                                                                                                                                                                                                    fontSize: c.cellFontSize,
                                                                                                                                                                                                                                                                                                                                              fontStyle: c.cellBold ? (c.cellItalic ? 'bolditalic' : 'bold') : (c.cellItalic ? 'italic' : 'normal'),
                                                                                                                                                                                                                                                                                                                                                        halign: c.cellHAlign,
                                                                                                                                                                                                                                                                                                                                                                  valign: c.cellVAlign,
                                                                                                                                                                                                                                                                                                                                                                            cellPadding: 2, // Adjust for wrap
                                                                                                                                                                                                                                                                                                                                                                                      overflow: c.cellWrap ? 'linebreak' : 'ellipsize',
                                                                                                                                                                                                                                                                                                                                                                                              };
                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                          autoTable(doc, {
                                                                                                                                                                                                                                                                                                                                                                                                                  startY: settings.headerHeight || 60,
                                                                                                                                                                                                                                                                                                                                                                                                                          margin: { top: settings.headerHeight || 60, bottom: 45 },
                                                                                                                                                                                                                                                                                                                                                                                                                                  head: [cols.map(c => c.header)],
                                                                                                                                                                                                                                                                                                                                                                                                                                          body: hall.rows.map((r: any, i: number) => cols.map(c => c.dataKey === '_index' ? toArabicDigits(i + 1) : toArabicDigits(r[c.dataKey] ?? ""))),
                                                                                                                                                                                                                                                                                                                                                                                                                                                  styles: { font: "Amiri", lineWidth: 0.2 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                          headStyles: { halign: 'center', valign: 'middle' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  didParseCell: (data) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (data.section === 'head') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const colSetting = cols[data.column.index];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    data.cell.styles.fillColor = colSetting.headerBgColor;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                data.cell.styles.textColor = colSetting.headerTextColor;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            data.cell.styles.fontSize = colSetting.headerFontSize;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        data.cell.styles.fontStyle = colSetting.headerBold ? 'bold' : 'normal';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    data.cell.styles.halign = colSetting.headerHAlign;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                data.cell.styles.valign = colSetting.headerVAlign;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            data.cell.styles.overflow = colSetting.headerWrap ? 'linebreak' : 'ellipsize';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // Apply row height
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              data.row.height = cols[data.column.index].rowHeight || 10;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        columnStyles,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                didDrawPage: (data) => drawPageFrame(doc, settings, project, hall, data.pageNumber),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return new Response(doc.output("arraybuffer"), { headers: { "Content-Type": "application/pdf" } });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch (e: any) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return NextResponse.json({ error: e.message }, { status: 500 });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }