// src/workers/id-card.worker.ts
import jsPDF from "jspdf";
import JSZip from "jszip";

// --- TYPES ---
export interface IDCardData {
  beneficiaryName: string;
    governorate: string;
      district: string;
        uzla: string;
          village: string;
            beneficiaryId: string;
              cardExpiry: string;
              }

              // --- CONSTANTS ---
              const CARD_WIDTH = 85.6;  // ID-1 Standard
              const CARD_HEIGHT = 53.98;
              const MARGIN = 3;

              // --- COLORS ---
              const COLORS = {
                BROWN_DARK: "#4e3629",   
                  BROWN_MEDIUM: "#795548", 
                    GOLD: "#d4af37",         
                      GOLD_LIGHT: "#f3e5ab",   
                        TEXT_DARK: "#1a1a1a",
                          TEXT_GRAY: "#4a4a4a",
                            RED_WARNING: "#b71c1c",
                              WHITE: "#FFFFFF"
                              };

                              // --- HELPER: DRAW ARABIC TEXT ---
                              function drawText(doc: jsPDF, text: string, x: number, y: number, size: number, color: string, align: "left" | "center" | "right" = "right", isBold = false) {
                                doc.setTextColor(color);
                                  doc.setFont("Amiri", isBold ? "bold" : "normal");
                                    doc.setFontSize(size);
                                      doc.text(String(text || ''), x, y, { align, baseline: "middle" });
                                      }

                                      // --- HELPER: DRAW SFD LOGO BOXES (Top Left) ---
                                      function drawLogoBoxes(doc: jsPDF, x: number, y: number) {
                                        const boxSize = 3.5;
                                          const gap = 0.5;
                                            
                                              doc.setDrawColor(255, 255, 255);
                                                doc.setLineWidth(0.1);

                                                  // Box 1 (Gold)
                                                    doc.setFillColor(COLORS.GOLD);
                                                      doc.rect(x, y, boxSize, boxSize, "FD");
                                                        doc.setTextColor(COLORS.BROWN_DARK);
                                                          doc.setFontSize(5);
                                                            doc.text("S", x + boxSize/2, y + boxSize/2 + 0.3, { align: "center", baseline: "middle" });

                                                              // Box 2 (White)
                                                                doc.setFillColor(COLORS.WHITE);
                                                                  doc.rect(x + boxSize + gap, y, boxSize, boxSize, "FD");
                                                                    doc.text("F", x + boxSize + gap + boxSize/2, y + boxSize/2 + 0.3, { align: "center", baseline: "middle" });

                                                                      // Box 3 (Dark Brown)
                                                                        doc.setFillColor(COLORS.BROWN_DARK);
                                                                          doc.rect(x + (boxSize + gap) * 2, y, boxSize, boxSize, "FD");
                                                                            doc.setTextColor(COLORS.WHITE);
                                                                              doc.text("D", x + (boxSize + gap) * 2 + boxSize/2, y + boxSize/2 + 0.3, { align: "center", baseline: "middle" });
                                                                              }

                                                                              // --- HELPER: HEADER DECORATION (Curves) ---
                                                                              function drawHeaderDecoration(doc: jsPDF) {
                                                                                doc.setFillColor(255, 255, 255);
                                                                                  doc.rect(0, 0, CARD_WIDTH, CARD_HEIGHT, "F");

                                                                                    // 1. Gold Wave (Background)
                                                                                      doc.setFillColor(COLORS.GOLD);
                                                                                        doc.path([
                                                                                            { op: 'm', c: [0, 0] },
                                                                                                { op: 'l', c: [CARD_WIDTH, 0] },
                                                                                                    { op: 'l', c: [CARD_WIDTH, 14] }, 
                                                                                                        { op: 'c', c: [60, 20, 20, 8, 0, 16] },
                                                                                                            { op: 'h', c: [] }
                                                                                                              ]).fill();

                                                                                                                // 2. Brown Wave (Foreground)
                                                                                                                  doc.setFillColor(COLORS.BROWN_DARK);
                                                                                                                    doc.path([
                                                                                                                        { op: 'm', c: [0, 0] },
                                                                                                                            { op: 'l', c: [CARD_WIDTH, 0] },
                                                                                                                                { op: 'l', c: [CARD_WIDTH, 12] },
                                                                                                                                    { op: 'c', c: [60, 18, 20, 6, 0, 14] },
                                                                                                                                        { op: 'h', c: [] }
                                                                                                                                          ]).fill();

                                                                                                                                            drawLogoBoxes(doc, 3, 3);
                                                                                                                                            }

                                                                                                                                            // --- HELPER: BOTTOM RIGHT DECORATIONS (Gold Triangle & Curves) ---
                                                                                                                                            function drawBottomDecorations(doc: jsPDF) {
                                                                                                                                              // 1. Gold Triangle / Shape at Bottom Right
                                                                                                                                                doc.setFillColor(COLORS.GOLD);
                                                                                                                                                  doc.path([
                                                                                                                                                      { op: 'm', c: [CARD_WIDTH, CARD_HEIGHT] },      // Bottom Right Corner
                                                                                                                                                          { op: 'l', c: [CARD_WIDTH, CARD_HEIGHT - 25] }, // Up the right edge
                                                                                                                                                              { op: 'c', c: [CARD_WIDTH - 10, CARD_HEIGHT - 15, CARD_WIDTH - 25, CARD_HEIGHT - 5, CARD_WIDTH - 40, CARD_HEIGHT] }, // Curve to bottom
                                                                                                                                                                  { op: 'h', c: [] }
                                                                                                                                                                    ]).fill();

                                                                                                                                                                      // 2. Dark Brown Shape overlapping it slightly (Footer background)
                                                                                                                                                                        doc.setFillColor(COLORS.BROWN_DARK);
                                                                                                                                                                          doc.path([
                                                                                                                                                                              { op: 'm', c: [0, CARD_HEIGHT] },
                                                                                                                                                                                  { op: 'l', c: [CARD_WIDTH, CARD_HEIGHT] },
                                                                                                                                                                                      { op: 'l', c: [CARD_WIDTH, CARD_HEIGHT - 4] },
                                                                                                                                                                                          { op: 'c', c: [CARD_WIDTH - 20, CARD_HEIGHT - 4, 20, CARD_HEIGHT - 4, 0, CARD_HEIGHT - 4] },
                                                                                                                                                                                              { op: 'h', c: [] }
                                                                                                                                                                                                ]).fill();
                                                                                                                                                                                                  
                                                                                                                                                                                                    // 3. Thin Gold Line on top of the footer bar
                                                                                                                                                                                                      doc.setDrawColor(COLORS.GOLD);
                                                                                                                                                                                                        doc.setLineWidth(0.5);
                                                                                                                                                                                                          doc.line(0, CARD_HEIGHT - 4, CARD_WIDTH, CARD_HEIGHT - 4);
                                                                                                                                                                                                          }

                                                                                                                                                                                                          // --- SIDE 1: FRONT OF CARD ---
                                                                                                                                                                                                          export function drawCardFront(doc: jsPDF, data: IDCardData) {
                                                                                                                                                                                                            drawHeaderDecoration(doc);
                                                                                                                                                                                                              drawBottomDecorations(doc); // <--- Added the specific bottom shapes

                                                                                                                                                                                                                // Header Text
                                                                                                                                                                                                                  drawText(doc, "الصندوق الاجتماعي للتنمية", CARD_WIDTH / 2, 4, 8, COLORS.WHITE, "center", true);
                                                                                                                                                                                                                    drawText(doc, "برنامج التحويلات النقدية المشروطة في التغذية", CARD_WIDTH / 2, 8, 6.5, COLORS.GOLD, "center", false);

                                                                                                                                                                                                                      // Title Box
                                                                                                                                                                                                                        doc.setDrawColor(COLORS.GOLD);
                                                                                                                                                                                                                          doc.setFillColor(252, 252, 250);
                                                                                                                                                                                                                            doc.setLineWidth(0.2);
                                                                                                                                                                                                                              doc.roundedRect(CARD_WIDTH - 28, 15, 25, 5.5, 1, 1, "FD");
                                                                                                                                                                                                                                drawText(doc, "بطاقة مستفيدة", CARD_WIDTH - 15.5, 18, 8, COLORS.BROWN_DARK, "center", true);

                                                                                                                                                                                                                                  // Data Fields
                                                                                                                                                                                                                                    const startY = 24;
                                                                                                                                                                                                                                      const rowH = 4.8;
                                                                                                                                                                                                                                        const labelX = CARD_WIDTH - MARGIN;
                                                                                                                                                                                                                                          const valX = CARD_WIDTH - 24;

                                                                                                                                                                                                                                            const drawRow = (label: string, value: string, y: number) => {
                                                                                                                                                                                                                                                drawText(doc, label + ":", labelX, y, 7, COLORS.TEXT_GRAY, "right");
                                                                                                                                                                                                                                                    drawText(doc, value, valX, y, 7.5, COLORS.TEXT_DARK, "right", true);
                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                        drawRow("الاسم", data.beneficiaryName, startY);
                                                                                                                                                                                                                                                          drawRow("المحافظة/المديرية", `${data.governorate} / ${data.district}`, startY + rowH);
                                                                                                                                                                                                                                                            drawRow("العزلة/القرية", `${data.uzla} / ${data.village}`, startY + (rowH * 2));

                                                                                                                                                                                                                                                              // ID & Expiry Boxes
                                                                                                                                                                                                                                                                const boxY = startY + (rowH * 3) + 2;
                                                                                                                                                                                                                                                                  const boxH = 8;
                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                      // ID Box
                                                                                                                                                                                                                                                                        doc.setDrawColor(COLORS.BROWN_DARK);
                                                                                                                                                                                                                                                                          doc.setLineWidth(0.3);
                                                                                                                                                                                                                                                                            doc.rect(CARD_WIDTH - 36, boxY, 33, boxH);
                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                doc.setFillColor(COLORS.BROWN_DARK);
                                                                                                                                                                                                                                                                                  doc.rect(CARD_WIDTH - 36, boxY, 33, 3, "F");
                                                                                                                                                                                                                                                                                    drawText(doc, "رقم البطاقة", CARD_WIDTH - 19.5, boxY + 1.5, 6, COLORS.WHITE, "center", true);
                                                                                                                                                                                                                                                                                      drawText(doc, data.beneficiaryId, CARD_WIDTH - 19.5, boxY + 6, 9, COLORS.TEXT_DARK, "center", true);

                                                                                                                                                                                                                                                                                        // Expiry Box
                                                                                                                                                                                                                                                                                          doc.setDrawColor(COLORS.RED_WARNING);
                                                                                                                                                                                                                                                                                            doc.rect(CARD_WIDTH - 66, boxY, 28, boxH);
                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                doc.setFillColor(COLORS.RED_WARNING);
                                                                                                                                                                                                                                                                                                  doc.rect(CARD_WIDTH - 66, boxY, 28, 3, "F");
                                                                                                                                                                                                                                                                                                    drawText(doc, "تاريخ الانتهاء", CARD_WIDTH - 52, boxY + 1.5, 6, COLORS.WHITE, "center", true);
                                                                                                                                                                                                                                                                                                      drawText(doc, data.cardExpiry, CARD_WIDTH - 52, boxY + 6, 8, COLORS.TEXT_DARK, "center", true);

                                                                                                                                                                                                                                                                                                        // Photo Placeholder
                                                                                                                                                                                                                                                                                                          doc.setDrawColor(COLORS.GOLD);
                                                                                                                                                                                                                                                                                                            doc.setLineWidth(0.4);
                                                                                                                                                                                                                                                                                                              doc.rect(3, 16, 21, 26); // Adjusted height to not overlap footer too much
                                                                                                                                                                                                                                                                                                                drawText(doc, "صورة", 13.5, 27, 6, "#cccccc", "center");
                                                                                                                                                                                                                                                                                                                  drawText(doc, "المستفيدة", 13.5, 30, 6, "#cccccc", "center");

                                                                                                                                                                                                                                                                                                                    // Footer Text
                                                                                                                                                                                                                                                                                                                      doc.setTextColor(COLORS.WHITE);
                                                                                                                                                                                                                                                                                                                        doc.setFontSize(5);
                                                                                                                                                                                                                                                                                                                          doc.text("Social Fund for Development - Nutrition CCT Program", CARD_WIDTH / 2, CARD_HEIGHT - 1.5, { align: "center", baseline: "middle" });
                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                          // --- SIDE 2: BACK OF CARD ---
                                                                                                                                                                                                                                                                                                                          export function drawCardBack(doc: jsPDF) {
                                                                                                                                                                                                                                                                                                                            doc.setFillColor(255, 255, 255);
                                                                                                                                                                                                                                                                                                                              doc.rect(0, 0, CARD_WIDTH, CARD_HEIGHT, "F");

                                                                                                                                                                                                                                                                                                                                // Header Bar
                                                                                                                                                                                                                                                                                                                                  doc.setFillColor(COLORS.BROWN_DARK);
                                                                                                                                                                                                                                                                                                                                    doc.rect(0, 0, CARD_WIDTH, 9, "F");
                                                                                                                                                                                                                                                                                                                                      doc.setDrawColor(COLORS.GOLD);
                                                                                                                                                                                                                                                                                                                                        doc.setLineWidth(0.8);
                                                                                                                                                                                                                                                                                                                                          doc.line(0, 9, CARD_WIDTH, 9);

                                                                                                                                                                                                                                                                                                                                            drawText(doc, "تعليمات هامة", CARD_WIDTH / 2, 4.5, 9, COLORS.WHITE, "center", true);

                                                                                                                                                                                                                                                                                                                                              // Instructions
                                                                                                                                                                                                                                                                                                                                                const startY = 15;
                                                                                                                                                                                                                                                                                                                                                  const step = 4.5;
                                                                                                                                                                                                                                                                                                                                                    const x = CARD_WIDTH - MARGIN;
                                                                                                                                                                                                                                                                                                                                                      const rules = [
                                                                                                                                                                                                                                                                                                                                                          "• البطاقة مخصصة لأنشطة البرنامج ولا يجوز استخدامها لأغراض أخرى.",
                                                                                                                                                                                                                                                                                                                                                              "• أي كشط أو تعديل في بيانات البطاقة يلغيها.",
                                                                                                                                                                                                                                                                                                                                                                  "• تحصل كل إمرأة امتثلت لشروط البرنامج على مبلغ 20 ألف ريال شهريا خلال",
                                                                                                                                                                                                                                                                                                                                                                      "  مدة تنفيذ المشروع ولا يحق لها التنازل عنه للغير جزئيا أو كليا.",
                                                                                                                                                                                                                                                                                                                                                                          "• عند اجبار المستفيدة على دفع أو خصم مبلغ منها يتم ابلاغ إدارة البرنامج فورا.",
                                                                                                                                                                                                                                                                                                                                                                              "• للإبلاغ عن فقدان البطاقة أو تقديم شكوى أو استفسار تواصل معنا."
                                                                                                                                                                                                                                                                                                                                                                                ];

                                                                                                                                                                                                                                                                                                                                                                                  rules.forEach((rule, i) => {
                                                                                                                                                                                                                                                                                                                                                                                      const isIndented = rule.startsWith("  ");
                                                                                                                                                                                                                                                                                                                                                                                          const yPos = startY + (i * step) - (isIndented ? 1.5 : 0);
                                                                                                                                                                                                                                                                                                                                                                                              drawText(doc, rule, x, yPos, 6, COLORS.TEXT_DARK, "right");
                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                  // Footer
                                                                                                                                                                                                                                                                                                                                                                                                    const footY = CARD_HEIGHT - 13;
                                                                                                                                                                                                                                                                                                                                                                                                      doc.setDrawColor(COLORS.GOLD);
                                                                                                                                                                                                                                                                                                                                                                                                        doc.setLineWidth(0.5);
                                                                                                                                                                                                                                                                                                                                                                                                          doc.line(MARGIN, footY, CARD_WIDTH - MARGIN, footY);

                                                                                                                                                                                                                                                                                                                                                                                                            drawText(doc, "للشكاوى والاستفسارات يرجى التواصل عبر الوسائل التالية:", CARD_WIDTH / 2, footY + 4, 7, COLORS.BROWN_DARK, "center", true);
                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                doc.setFontSize(8);
                                                                                                                                                                                                                                                                                                                                                                                                                  doc.setTextColor(COLORS.TEXT_DARK);
                                                                                                                                                                                                                                                                                                                                                                                                                    doc.text("الرقم المجاني: 8009800   |   الرقم الثابت: 513821 - 01", CARD_WIDTH / 2, footY + 9, { align: "center", baseline: "middle" });
                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                    // --- WORKER LOGIC ---
                                                                                                                                                                                                                                                                                                                                                                                                                    self.onmessage = async (event) => {
                                                                                                                                                                                                                                                                                                                                                                                                                        const { beneficiaries, fontBase64 } = event.data;

                                                                                                                                                                                                                                                                                                                                                                                                                            if (!beneficiaries || !fontBase64) {
                                                                                                                                                                                                                                                                                                                                                                                                                                    postMessage({ type: 'error', error: 'Missing beneficiaries data or font.' });
                                                                                                                                                                                                                                                                                                                                                                                                                                            return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                    try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            const grouped: Record<string, any[]> = {};
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    beneficiaries.forEach((row: any) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const edu = row.ED_NAME || "Unassigned";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (!grouped[edu]) grouped[edu] = [];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        grouped[edu].push(row);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const zip = new JSZip();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const totalEducators = Object.keys(grouped).length;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        let educatorsProcessed = 0;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for (const [educator, bnfs] of Object.entries(grouped)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: [CARD_WIDTH, CARD_HEIGHT] });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        doc.addFileToVFS("Amiri-Regular.ttf", fontBase64);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    doc.addFont("Amiri-Regular.ttf", "Amiri", "normal");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                doc.addFont("Amiri-Regular.ttf", "Amiri", "bold");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            bnfs.forEach((bnf, index) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (index > 0) doc.addPage([CARD_WIDTH, CARD_HEIGHT], "landscape");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const cardData: IDCardData = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              beneficiaryName: bnf.l_benef_name || 'N/A',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                governorate: bnf.gov_name || '',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  district: bnf.mud_name || '',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    uzla: bnf.hh_ozla_name || '',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      village: bnf.hh_vill_name || '',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        beneficiaryId: String(bnf.l_id || ''),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          cardExpiry: bnf.expiry_date || "2025-01-31" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          drawCardFront(doc, cardData);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          doc.addPage([CARD_WIDTH, CARD_HEIGHT], "landscape");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          drawCardBack(doc);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const safeName = educator.replace(/[^a-zA-Z0-9\u0600-\u06FF \-_]/g, "_").trim();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              zip.file(`${safeName}_ID_Cards.pdf`, doc.output("arraybuffer"));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      educatorsProcessed++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  postMessage({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  type: 'progress',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  status: `Generating PDFs for ${safeName}...`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  progress: Math.round((educatorsProcessed / totalEducators) * 100),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  current: educatorsProcessed,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  total: totalEducators
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      postMessage({ type: 'progress', status: 'Zipping files...', progress: 100 });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const zipContent = await zip.generateAsync({ type: "arraybuffer" });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      self.postMessage({ type: 'done', data: zipContent }, [zipContent]);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          } catch (error: any) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  console.error(error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          postMessage({ type: 'error', error: error.message });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };