
"use client";

import React, { useState } from "react";
import type { RecordRow } from "@/lib/types";
import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription, SheetFooter } from "@/components/ui/sheet";
import { Microscope, Sparkles, Loader2 } from "lucide-react";

type Cluster = RecordRow[];

interface ClusterCardProps {
  cluster: Cluster;
  clusterNumber: number;
  onInspect: () => void;
}

export function ClusterCard({ cluster, clusterNumber, onInspect }: ClusterCardProps) {
  const [aiSummary, setAiSummary] = useState<string | null>(null);
  const [loadingSummary, setLoadingSummary] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [isPanelOpen, setIsPanelOpen] = useState(false);

  const generateSummary = async () => {
    if (loadingSummary) return;

    setLoadingSummary(true);
    setError(null);
    try {
      const res = await fetch('/api/ai/describe-cluster', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ cluster }),
      });
      if (!res.ok) {
        const errData = await res.json();
        throw new Error(errData.error || "Failed to fetch summary from server.");
      }
      const data = await res.json();
      setAiSummary(data.summary);
    } catch (e: any) {
      setError(e.message || "An unknown error occurred.");
    } finally {
      setLoadingSummary(false);
    }
  };
  
  const handleOpenPanel = () => {
      setIsPanelOpen(true);
      if (!aiSummary) {
          generateSummary();
      }
  }

  return (
    <>
      <Card className="flex flex-col hover:shadow-md transition-shadow">
        <CardHeader>
          <CardTitle>Cluster {clusterNumber}</CardTitle>
          <CardDescription>{cluster.length} records</CardDescription>
        </CardHeader>
        <CardContent className="flex-1 space-y-4">
          <div className="space-y-2 text-sm">
            {cluster.map((r, i) => (
              <p key={i} className="truncate" title={r.womanName}>
                {r.womanName}
              </p>
            ))}
          </div>
        </CardContent>
        <CardFooter className="flex flex-col sm:flex-row gap-2">
          <Button variant="outline" className="w-full" onClick={onInspect}>
            <Microscope className="mr-2 h-4 w-4" />
            Inspect
          </Button>
          <Button variant="default" className="w-full" onClick={handleOpenPanel}>
            <Sparkles className="mr-2 h-4 w-4 text-purple-300" />
            AI Summary
          </Button>
        </CardFooter>
      </Card>
      
      <Sheet open={isPanelOpen} onOpenChange={setIsPanelOpen}>
          <SheetContent>
              <SheetHeader>
                  <SheetTitle>AI-Powered Summary for Cluster {clusterNumber}</SheetTitle>
                  <SheetDescription>
                      This summary is generated by AI to highlight key similarities and potential reasons for grouping these records.
                  </SheetDescription>
              </SheetHeader>
              <div className="py-4">
                  {loadingSummary && (
                      <div className="flex items-center justify-center h-40">
                          <Loader2 className="h-8 w-8 animate-spin text-primary" />
                      </div>
                  )}
                  {error && (
                      <div className="text-destructive p-4 bg-destructive/10 rounded-md">
                          <h4 className="font-semibold">Error</h4>
                          <p>{error}</p>
                      </div>
                  )}
                  {aiSummary && (
                      <div className="p-4 bg-muted/50 rounded-md text-sm whitespace-pre-wrap">
                          {aiSummary}
                      </div>
                  )}
              </div>
              <SheetFooter>
                 <Button variant="outline" onClick={() => setIsPanelOpen(false)}>Close</Button>
              </SheetFooter>
          </SheetContent>
      </Sheet>
    </>
  );
}

