
"use client";

import React, { useState } from "react";
import type { RecordRow } from "@/lib/types";
import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription, SheetFooter } from "@/components/ui/sheet";
import { Microscope, Sparkles, Loader2 } from "lucide-react";

type Cluster = RecordRow[];

interface ClusterCardProps {
  cluster: Cluster;
  clusterId: string;
  clusterNumber: number;
  onInspect: () => void;
  onGenerateSummary: () => void;
  aiSummary: string | null | undefined;
  isSummaryLoading: boolean | undefined;
  summaryError: string | null | undefined;
}

export function ClusterCard({ cluster, clusterId, clusterNumber, onInspect, onGenerateSummary, aiSummary, isSummaryLoading, summaryError }: ClusterCardProps) {
  const [isPanelOpen, setIsPanelOpen] = useState(false);

  const handleOpenPanel = () => {
      setIsPanelOpen(true);
      // Only generate if there's no summary and it's not already loading
      if (!aiSummary && !isSummaryLoading) {
          onGenerateSummary();
      }
  }

  return (
    <>
      <Card className="flex flex-col hover:shadow-md transition-shadow">
        <CardHeader>
          <CardTitle>Cluster {clusterNumber}</CardTitle>
          <CardDescription>{cluster.length} records</CardDescription>
        </CardHeader>
        <CardContent className="flex-1 space-y-4">
          <div className="space-y-2 text-sm">
            {cluster.map((r, i) => (
              <p key={i} className="truncate" title={r.womanName}>
                {r.womanName}
              </p>
            ))}
          </div>
        </CardContent>
        <CardFooter className="flex flex-col sm:flex-row gap-2">
          <Button variant="outline" className="w-full" onClick={onInspect}>
            <Microscope className="mr-2 h-4 w-4" />
            Inspect
          </Button>
          <Button variant="default" className="w-full" onClick={handleOpenPanel} disabled={isSummaryLoading}>
             {isSummaryLoading ? (
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
             ) : (
                <Sparkles className="mr-2 h-4 w-4 text-purple-300" />
             )}
            AI Summary
          </Button>
        </CardFooter>
      </Card>
      
      <Sheet open={isPanelOpen} onOpenChange={setIsPanelOpen}>
          <SheetContent className="sm:max-w-lg">
              <SheetHeader>
                  <SheetTitle>AI-Powered Summary for Cluster {clusterNumber}</SheetTitle>
                  <SheetDescription>
                      This summary is generated by AI to highlight key similarities and potential reasons for grouping these records.
                  </SheetDescription>
              </SheetHeader>
              <div className="py-4">
                  {isSummaryLoading && (
                      <div className="flex items-center justify-center h-40">
                          <Loader2 className="h-8 w-8 animate-spin text-primary" />
                          <p className="ml-2">Generating summary...</p>
                      </div>
                  )}
                  {summaryError && (
                      <div className="text-destructive p-4 bg-destructive/10 rounded-md">
                          <h4 className="font-semibold">Error</h4>
                          <p>{summaryError}</p>
                      </div>
                  )}
                  {aiSummary && (
                      <div className="p-4 bg-muted/50 rounded-md text-sm whitespace-pre-wrap" dir="rtl">
                          {aiSummary}
                      </div>
                  )}
              </div>
              <SheetFooter>
                 <Button variant="outline" onClick={() => setIsPanelOpen(false)}>Close</Button>
              </SheetFooter>
          </SheetContent>
      </Sheet>
    </>
  );
}
